
services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-bullyguard}"
    image: bullyguard-model
    container_name: bullyguard-model-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-bar3126}"
        USER_ID: "${USER_ID:-1000}"
    # env_file:
    #  - .envs/.app
    volumes:
      - ./:/app/
      - ~/.config/gcloud:${HOME}/.config/gcloud
    ports:
      - 8080:8080

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    init: true

      